//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxdonRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTbl()
        {
            this.ProductImageTbls = new HashSet<ProductImageTbl>();
        }
    
        public long ProductID { get; set; }
        public Nullable<long> CatID { get; set; }
        public Nullable<long> ShopID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductMRP { get; set; }
        public Nullable<int> SellingPrice { get; set; }
        public Nullable<int> FoxdonPrice { get; set; }
    
        public virtual CategoryTbl CategoryTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImageTbl> ProductImageTbls { get; set; }
        public virtual ShopTbl ShopTbl { get; set; }
    }
}
